In [84]:
using LinearAlgebra

In [506]:
A = rand(1000,1000)

1000×1000 Array{Float64,2}:
 0.556877  0.0602514  0.425808   …  0.268598   0.732371   0.0512756
 0.546841  0.979085   0.146611      0.0438357  0.0270988  0.333461 
 0.818094  0.747136   0.517279      0.888624   0.966643   0.407537 
 0.794305  0.528252   0.4925        0.631243   0.967172   0.932269 
 0.65892   0.994676   0.233979      0.279515   0.749487   0.747211 
 0.562283  0.633411   0.253269   …  0.275644   0.819488   0.762434 
 0.461226  0.405975   0.996231      0.326945   0.896154   0.967486 
 0.18095   0.344724   0.240751      0.817705   0.907245   0.278696 
 0.449745  0.0395835  0.519124      0.649622   0.07277    0.483511 
 0.68622   0.779952   0.389819      0.519592   0.876634   0.279607 
 0.292054  0.729301   0.0417727  …  0.901318   0.702709   0.705319 
 0.407033  0.021517   0.559628      0.102112   0.873404   0.655277 
 0.854201  0.587779   0.272877      0.142201   0.749039   0.953906 
 ⋮                               ⋱                                 
 0.250292  0.977552 

In [507]:
b = rand(1000,1);

In [522]:
A1 = rand(500,500);
b1 = rand(500,1);

In [524]:
@time(\(A1,b1))

  0.084243 seconds (9 allocations: 1.916 MiB)


500×1 Array{Float64,2}:
  3.5134066544717513 
 -3.309603077650202  
  1.7370318630743609 
  0.6180905888045921 
  3.2863885854869856 
  2.6169896575844342 
  1.6137634357756756 
 -1.022252160988077  
 -0.2014769715041294 
 -0.25502994894696157
 -2.688884931038663  
 -5.7949350150370735 
 -0.23649651155664508
  ⋮                  
 -0.17571542063848694
 -5.167627699141157  
 -0.7971200783003082 
 -2.4407224548175526 
 -3.5860661854419567 
 -3.8242405006391182 
  0.5237183470708963 
 -4.211941065695086  
 -2.476641455203631  
 -2.571860391381598  
 -0.10171283587579992
 -1.67586422249136   

In [504]:
function gaussRow(A)
    #A=B
    n = size(A)[1]
    print(size(A))
    #A = zeros(n,n+1)
    #transpose!(A,B')
    #n = size(A)[1]
    for i = 1:n
        #maxRow = argmax(A[i:n,i])+i-1#max i column
        #tmp = A[maxRow,:]#column swap
        #A[maxRow,:] = A[i,:]
        #A[i,:] = tmp
        
        for k = i+1:n#zeroing next row
            c = -A[k,i]/A[i,i]
            A[k,i:n+1] = A[k,i:n+1] .+ c .* A[i,i:n+1]
            A[k,i] = 0
        end
    end
    #print(A)
    x = zeros(n)
    for i = n:-1:1#finding xs
        x[i] = A[i,n+1]/A[i,i]
        A[i-1:-1:1,n+1] -= A[i-1:-1:1,i] .* x[i]
    end
    return x
    
end

gaussRow (generic function with 1 method)

In [500]:
function gaussColumn(A)
    #A=B
    n = size(A)[2]
    #print(size(A))
    #A = zeros(n,n+1)
    #transpose!(A,B')
    #n = size(A)[1]
    #print(A)
    for i = 1:n
        #maxRow = argmax(A[i,i:n])+i-1#max i column
        #tmp = A[:,maxRow]#column swap
        #A[:,maxRow] = A[:,i]
        #A[:,i] = tmp
        for k = i+1:n#zeroing next row
            c = -A[i,k]/A[i,i]
            A[i:n+1,k] = A[i:n+1,k] .+ c .* A[i:n+1,i]
            A[i,k] = 0
        end
    end
    #print(A)
    x = zeros(n)
    for i = n:-1:1#finding xs
        x[i] = A[n+1,i]/A[i,i]
        A[n+1,i-1:-1:1] -= A[i,i-1:-1:1] .* x[i]
    end
    return x
    
end

gaussColumn (generic function with 1 method)

In [525]:
m1 = hcat(A,b)
n = size(m1)[1]
m2 = zeros(n+1,n)
transpose!(m2,m1)
@time(x = gaussColumn(m2))

  3.791936 seconds (1.50 M allocations: 7.694 GiB, 18.79% gc time)


1000-element Array{Float64,1}:
 -2.6848285382346635 
  1.9026806373248448 
 -6.882272855294859  
 -2.452532105985505  
 -4.418280895925517  
 -0.06882859898221992
 -1.0374789708491392 
 -4.452470413961924  
 -2.366021267815613  
  5.963290175508148  
  1.1355389583784163 
 -2.705698319104925  
 -1.3662589119464967 
  ⋮                  
 -4.921918892877736  
  3.4723923710447258 
 -2.0674738672310577 
 -0.2853019893761499 
 -1.2499892568555804 
  4.654370876480343  
 -0.06897726820175737
 -1.2714592357510304 
  4.517912920990737  
 -7.39776220545493   
 -1.4580370753590837 
  7.430975880933352  

In [526]:
m1 = hcat(A,b)
@time(x = gaussRow(m1))

(1000, 1001)  5.423913 seconds (1.50 M allocations: 7.694 GiB, 13.34% gc time)


1000-element Array{Float64,1}:
 -2.6848285382346635 
  1.9026806373248448 
 -6.882272855294859  
 -2.452532105985505  
 -4.418280895925517  
 -0.06882859898221992
 -1.0374789708491392 
 -4.452470413961924  
 -2.366021267815613  
  5.963290175508148  
  1.1355389583784163 
 -2.705698319104925  
 -1.3662589119464967 
  ⋮                  
 -4.921918892877736  
  3.4723923710447258 
 -2.0674738672310577 
 -0.2853019893761499 
 -1.2499892568555804 
  4.654370876480343  
 -0.06897726820175737
 -1.2714592357510304 
  4.517912920990737  
 -7.39776220545493   
 -1.4580370753590837 
  7.430975880933352  

In [527]:
m1 = hcat(A1,b1)
n = size(m1)[1]
m2 = zeros(n+1,n)
transpose!(m2,m1)
@time(x = gaussColumn(m2))
m1 = hcat(A1,b1)
@time(x = gaussRow(m1))

  0.573966 seconds (376.25 k allocations: 1015.246 MiB, 20.72% gc time)
(500, 501)  0.741304 seconds (376.35 k allocations: 1015.248 MiB, 27.39% gc time)


500-element Array{Float64,1}:
  3.513406653722628 
 -3.3096030767484312
  1.737031863448517 
  0.6180905889775398
  3.286388585661986 
  2.6169896574517315
  1.613763435729126 
 -1.0222521614053672
 -0.2014769716752197
 -0.2550299491877055
 -2.6888849304140856
 -5.794935014660772 
 -0.2364965117924942
  ⋮                 
 -0.1757154203132392
 -5.167627699318477 
 -0.7971200784751492
 -2.440722454547602 
 -3.5860661850787054
 -3.8242405004228406
  0.5237183471855933
 -4.211941065476658 
 -2.476641455069782 
 -2.5718603914242144
 -0.1017128357576028
 -1.6758642225672025

In [213]:
solve1 = hcat(A,b)
factorize(A)

LU{Float64,Array{Float64,2}}
L factor:
10×10 Array{Float64,2}:
 1.0         0.0        0.0        0.0        …   0.0        0.0       0.0
 0.0708237   1.0        0.0        0.0            0.0        0.0       0.0
 0.160583    0.425224   1.0        0.0            0.0        0.0       0.0
 0.578237    0.399973   0.651783   1.0            0.0        0.0       0.0
 0.751099    0.519196  -0.29692   -0.188037       0.0        0.0       0.0
 0.842764   -0.609414   0.777456  -0.781755   …   0.0        0.0       0.0
 0.160855    0.740978  -0.06617    0.0560897      0.0        0.0       0.0
 0.116747    0.105625   0.366365   0.0176396      1.0        0.0       0.0
 0.446266    0.456834   0.711658   0.40879       -0.594543   1.0       0.0
 0.73364     0.155262   0.340219   0.875213       0.44072   -0.144453  1.0
U factor:
10×10 Array{Float64,2}:
 0.886125  0.641443   0.519533    …   0.392864    0.141255    0.132919 
 0.0       0.833291  -0.00516572      0.209597    0.213955    0.620454 
 0.0     

In [ ]:
function gauss(B)
    A=B
    n = size(A)[1]
    for i = 1:n
        maxEl = abs(A[i,i])
        maxRow = i
        for k = i+1:n
            if abs(A[k,i]) > maxEl
                maxEl = abs(A[k,i])
                maxRow = k
            end
        end
        #maxRow = argmax(A[i:n,i])+i-1
        #maxEl = max
        for k = i:n+1
            tmp = A[maxRow,k]
            A[maxRow,k] = A[i,k]
            A[i,k] = tmp
        end
        #tmp = A[maxRow,:]
        #A[maxRow,:] = A[i,:]
        #A[i,:] = tmp
        # print(A, "\n")
        for k = i+1:n
            c = -A[k,i]/A[i,i]
            for j = i:n+1
                if i == j
                    A[k,j] = 0
                else
                    A[k,j] += c * A[i ,j]
                end
            end
        end
    end
    x = zeros(n)
    for i = n:-1:1
        x[i] = A[i,n+1]/A[i,i]
        
        for k = i-1:-1:1
            A[k,n+1] -= A[k,i] * x[i]
        end
        #A[i-1:-1:1,n+1] -= A[i-1:-1:1,i] .* x[i]
    end
    return x
    
end