In [61]:
import numpy as np
import math
import timeit

Zadanie 0. (rozgrzewkowe, 1 punkt, zadanie należy przesłać emailem)<br>
Utwórz skrypt definiujący poniższe zmienne:<br>
a = [1, 2, 3, 4, ..., 100] (wektor złożony z liczb całkowitych od 1 do 100)\newline<br>
b = [1, 3, 5, 7, ..., 99] (wektor złożony z liczb całkowitych nieparzystych od 1 do 99)<br>
c = [-1.00 * π, -0.99 * π, ..., -0.01 * π, 0, 0.01 * π, ..., 0.99 * π, 1.00 * π]<br>
d = [-1.00 * π, -0.99 * π, ..., -0.01 * π, 0.01 * π, ..., 0.99 * π, 1.00 * π]<br>
e = [e 1 , e 2 , ..., e 100 ], gdzie e i = sin(i), jeśli sin(i) > 0, lub e i = 0 w przeciwnym przypadku<br>


In [74]:
a = np.arange(1,101,1)#.tolist()
print('a =',a)
b = np.arange(1,101,2)
print('b = ',b)
%timeit c = np.linspace(-1*math.pi, 1*math.pi, 201).round(10) #zaokraglenia celem osiagnieca zera
#%timeit c = np.arange(-100.0,101.0,1).tolist(); c = [i *math.pi/100.0 for i in c]
#metoda nieco szybsza, brak zaokraglania
print('wybrane el. c ', c[0],c[100],c[200])
d = c[c != 0]
print('c bez zera ', d[99],d[100])
%timeit e = np.maximum(np.zeros(100), np.sin(np.arange(1,101,1))) #np sin zeby byla macierz
print('e = ', e) #okolo 8u vs 42u
#e = np.zeros(100)#nieefektywna - ponizej timeit 
#for i in range(1,101): 
 #   a = math.sin(i);
  #  if a>0:
   #     e[i-1] = a;
    #else:
     #   e[i-1] = 0


a = [  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
b =  [ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]
46.3 µs ± 1.91 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
wybrane el. c  -3.1415926536 0.0 3.1415926536
c bez zera  -0.0314159265 0.0314159265
8.16 µs ± 228 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
e =  [0.84147098 0.90929743 0.14112001 0.         0.         0.
 0.6569866  0.98935825 0.41211849 0.         0.         0.
 0.42016704 0.99060736 0.65028784 0.         0.         0.
 0.14987721 0.9

In [69]:
%%timeit
e = np.zeros(100)
for i in range(1,101): 
    a = math.sin(i);
    if a>0:
        e[i-1] = a;
    else:
        e[i-1] = 0


42.7 µs ± 631 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


zadanie 0 cześć druga<br>
A = macierz rozmiaru 10 x 10 zawierająca liczby całkowite od 1 do 100: w pierwszym wierszu od lewej 1, 2, ..., w drugim wierszu od lewej 11, 12, .., itd. (wskazówka: użyć polecenia reshape)<br>
B = macierz trójdiagonalna rozmiaru 100 x 100 mająca na głównej przekątnej liczby całkowite od 1
do 100, a poniżej i powyżej głównej przekątnej liczby od 99 do 1<br>
C = macierz trójkątna górna wypełniona jedynkami (łącznie z główną przekątną)<br>
D = macierz rozmiaru 2 x 100, w której pierwszy wiersz zawiera elementy d 1i = 1 + 2 + ... + i, a drugi wiersz zawiera elementy d 2i = i!<br>
E = macierz rozmiaru 100 x 100 mająca 1 w pozycji (i, j), jeśli i dzieli j, lub 0 w przeciwnym przypadku.<br>

In [106]:
A = np.arange(1,101).reshape((10,10))
print('A = ', A)
C = np.ones((10,10))
C = np.triu(C)
print('C = ', C)

d1 = np.cumsum(np.arange(1,101,1)) #suma skumulowana
d2 = np.cumprod(np.arange(1,101,1),dtype=np.float) #iloczyn skumulowany - faktorial + typ float
D = np.append(d1,d2).reshape(2,100) #najszybsza
#D = np.r_[d1,d2].reshape(2,100) #inne dodawanie
#print(D)
#D1 = np.empty([2,100])
#sum = 0
#pr = 1
#for i in range(100):#bardzo wolny for
 #   sum += (i+1)
  #  pr *= (i+1)
 #   D1[0][i] = sum
  #  D1[1][i] = pr
#print(D)

A =  [[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
C =  [[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [108]:
%%timeit
d1 = np.cumsum(np.arange(1,101,1)) #suma skumulowana
d2 = np.cumprod(np.arange(1,101,1),dtype=np.float) #iloczyn skumulowany - faktorial + typ float
D = np.r_[d1,d2].reshape(2,100)

41.6 µs ± 1.38 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [109]:
%%timeit
d1 = np.cumsum(np.arange(1,101,1)) #suma skumulowana
d2 = np.cumprod(np.arange(1,101,1),dtype=np.float) #iloczyn skumulowany - faktorial + typ float
D = np.append(d1,d2).reshape(2,100)

20 µs ± 331 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [107]:
%%timeit
D1 = np.empty([2,100])
sum = 0
pr = 1
for i in range(100):
    sum += (i+1)
    pr *= (i+1)
    D1[0][i] = sum
    D1[1][i] = pr


103 µs ± 3.52 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [122]:
E = np.zeros([100,100])
for i in range(1,101):
    for j in range(1,101):
        if j%i == 0:
            E[i-1][j-1]=1
#duzo gorsza wydajnosc           
#E1 = np.array([[1 if j%i == 0 else 0 for j in range(1,101)] for i in range(1,101)])
print(E1)
print(E)
v1 = np.arange(99,0,-1)
v2 = np.arange(1,101,1)
B = np.diag(v2) + np.diag(v1,k=1) + np.diag(v1,k=-1) #ladna implementacja k-> przesuniecie
print('B = ', B)
#B1 = np.eye(100) #wolniejsza 
#j=99
#for i in range(100):
 #   B1[i][i]*=(i+1)
  #  if i<99:
   #     B1[i][i+1]=j
    #    B1[i+1][i]=j
     #   j-=1
#print(B1)

[[1 1 1 ... 1 1 1]
 [0 1 0 ... 1 0 1]
 [0 0 1 ... 0 1 0]
 ...
 [0 0 0 ... 1 0 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
[[1. 1. 1. ... 1. 1. 1.]
 [0. 1. 0. ... 1. 0. 1.]
 [0. 0. 1. ... 0. 1. 0.]
 ...
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
B =  [[  1  99   0 ...   0   0   0]
 [ 99   2  98 ...   0   0   0]
 [  0  98   3 ...   0   0   0]
 ...
 [  0   0   0 ...  98   2   0]
 [  0   0   0 ...   2  99   1]
 [  0   0   0 ...   0   1 100]]


In [121]:
%%timeit
E = np.zeros([100,100])
for i in range(1,101):
    for j in range(1,101):
        if j%i == 0:
            E[i-1][j-1]=1


911 µs ± 47.5 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [120]:
%%timeit
E1 = np.array([[1 if j%i == 0 else 0 for j in range(1,101)] for i in range(1,101)])

2.15 ms ± 115 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [95]:
%%timeit
B1 = np.eye(100)
j=99
for i in range(100):
    B1[i][i]*=(i+1)
    if i<99:
        B1[i][i+1]=j
        B1[i+1][i]=j
        j-=1

178 µs ± 6.32 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [96]:
%%timeit
v1 = np.arange(99,0,-1)
v2 = np.arange(1,101,1)
B = np.diag(v2) + np.diag(v1,k=1) + np.diag(v1,k=-1) #ladna implementacja


48.6 µs ± 1.15 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)
