In [53]:
import numpy as np
import math
import random
import matplotlib.pyplot as plt
%matplotlib inline
params = {"ytick.color" : "c",
          "xtick.color" : "c",
          "axes.labelcolor" : "c",
          "axes.edgecolor" : "c",
         "text.color" : "c"}
plt.rcParams.update(params)

import pandas as pd
from sklearn.cluster import KMeans, MiniBatchKMeans, Birch, DBSCAN
from collections import Counter
from itertools import cycle
from sklearn import datasets, metrics, tree#silhouette
import scipy.stats as sstats

#from sklearn.decomposition import PCA
import seaborn as sns
from sklearn.model_selection import train_test_split
import tqdm

In [54]:
import graphviz

In [55]:
titanic_train = pd.read_csv('train_titanic.csv')
titanic_test = pd.read_csv('test_titanic.csv')
#drop irrelevant categories
X = titanic_train.drop(['PassengerId', 'Name', 'Ticket', 'Cabin'], axis = 1)
X = X.dropna()#remove missing values
X['Sex'] = pd.Categorical(X['Sex']).codes
X['Embarked'] = pd.Categorical(X['Embarked']).codes
#change to numerical values
X.head()


Survived  Pclass  Sex   Age  SibSp  Parch     Fare  Embarked
0         0       3    1  22.0      1      0   7.2500         2
1         1       1    0  38.0      1      0  71.2833         0
2         1       3    0  26.0      0      0   7.9250         2
3         1       1    0  35.0      1      0  53.1000         2
4         0       3    1  35.0      0      0   8.0500         2

In [56]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import ExtraTreesClassifier


In [57]:
# TITANIC
X_titanic_train, X_titanic_test = train_test_split(X, test_size=0.3333)
Y_titanic_train = X_titanic_train['Survived']
X_titanic_train = X_titanic_train.drop('Survived', axis=1)

Y_titanic_test = X_titanic_test['Survived']
X_titanic_test = X_titanic_test.drop('Survived', axis=1)

t = tree.DecisionTreeClassifier()
t = t.fit(X_titanic_train, Y_titanic_train)
with open("/home/oskar/titanic.dot", "w") as f:
    tree.export_graphviz(t, out_file=f, feature_names=X_titanic_train.columns)

In [59]:
#using  classifiers
random_forest = RandomForestClassifier(n_estimators=20)
extra_random_forest = ExtraTreesClassifier(n_estimators=20)

r1 = random_forest.fit(X_titanic_train, Y_titanic_train)
r2 = extra_random_forest.fit(X_titanic_train, Y_titanic_train);

In [60]:
print(f'Random Forest:')
print(metrics.confusion_matrix(random_forest.predict(X_titanic_test), Y_titanic_test))
print(f'Score: {random_forest.score(X_titanic_test, Y_titanic_test) * 100}%\n')

Random Forest:
[[115  28]
 [ 24  71]]
Score: 78.15126050420169%



In [61]:
print(f'Extremely Randomized Trees:')
print(metrics.confusion_matrix(extra_random_forest.predict(X_titanic_test), Y_titanic_test))
print(f'Score: {extra_random_forest.score(X_titanic_test, Y_titanic_test) * 100}%\n')


Extremely Randomized Trees:
[[110  32]
 [ 29  67]]
Score: 74.36974789915966%



In [62]:
# Iris
iris = datasets.load_iris()
iris_df = pd.DataFrame(iris.data, columns=iris.feature_names)
iris_df['species'] = pd.Categorical.from_codes(iris.target, iris.target_names)
iris_df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

  species  
0  setosa  
1  setosa  
2  setosa  
3  setosa  
4  setosa

In [63]:
X_iris_train, X_iris_test = train_test_split(iris_df, test_size=0.3333)
Y_iris_train = X_iris_train['species']
X_iris_train = X_iris_train.drop('species', axis=1)

Y_iris_test = X_iris_test['species']
X_iris_test = X_iris_test.drop('species', axis=1)

In [64]:
#n of decision tree classifiers on sub-samples
random_forest = RandomForestClassifier(n_estimators=20)# number of tress

extra_random_forest = ExtraTreesClassifier(n_estimators=20);

random_forest.fit(X_iris_train, Y_iris_train)
extra_random_forest.fit(X_iris_train, Y_iris_train);

In [65]:
print('Random Forest:')
print(metrics.confusion_matrix(random_forest.predict(X_iris_test), Y_iris_test))
print(f'Score: {random_forest.score(X_iris_test, Y_iris_test) * 100:.2f}%\n')

Random Forest:
[[18  0  0]
 [ 0 13  2]
 [ 0  1 16]]
Score: 94.00%



In [66]:
print('Extremely Randomized Trees:')
print(metrics.confusion_matrix(extra_random_forest.predict(X_iris_test), Y_iris_test))
print(f'Score: {extra_random_forest.score(X_iris_test, Y_iris_test) * 100:.2f}%\n')


Extremely Randomized Trees:
[[18  0  0]
 [ 0 13  1]
 [ 0  1 17]]
Score: 96.00%

